# Generated by Django 3.2.6 on 2023-01-18 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopperArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.article')),
                ('shopper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.shopper')),
            ],
        ),
    ]
