# Generated by Django 3.2.6 on 2023-01-18 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_shopperarticle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperarticle',
            name='note',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
