# Generated by Django 3.2.6 on 2023-01-18 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0003_alter_shopperarticle_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopperarticle',
            name='note',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
