# Generated by Django 3.2.6 on 2023-02-12 11:51

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0006_alter_article_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.CharField(max_length=128)),
                ('cotegorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ventes.categorie')),
            ],
        ),
        migrations.RemoveField(
            model_name='supplybasket',
            name='article',
        ),
        migrations.RemoveField(
            model_name='supplybasket',
            name='supply',
        ),
        migrations.AddField(
            model_name='article',
            name='state',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='commandebasket',
            name='signed',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='manager',
            name='state',
            field=models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.DeleteModel(
            name='Supply',
        ),
        migrations.DeleteModel(
            name='SupplyBasket',
        ),
    ]
