# Generated by Django 3.2.6 on 2023-02-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0007_auto_20230212_1151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategorie',
            old_name='cotegorie',
            new_name='categorie',
        ),
    ]
