# Generated by Django 3.2.6 on 2023-03-02 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0011_auto_20230302_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='designation',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
