# Generated by Django 3.2.18 on 2023-03-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0012_alter_article_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='contact',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shopper',
            name='contact',
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
    ]
