# Generated by Django 3.2.18 on 2023-03-24 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0013_auto_20230323_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='subcategorie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventes.categorie'),
        ),
    ]
